// Single source of truth for the version/changelog surfaced in-app
// (src/pages/Profile.jsx footer). Mirrors CHANGELOG.md's own section
// titles — keep package.json's "version" and this file's APP_VERSION in
// sync by hand on release, same convention as stockflow/cateqhub's
// appConfig.js. This file is never touched by `npm run build` — only ever
// bumped by hand alongside a real CHANGELOG.md entry.
export const APP_VERSION = '2.0.23';
export const RELEASE_DATE = '2026-10-05';

// Condensed from CHANGELOG.md's own entry titles — full detail lives there.
//
// Two summaries per entry, on purpose (módulo 21): `resumen` is what the
// About screen shows a user — plain Spanish, about what changed FOR THEM —
// while `summary` stays the faithful technical record mirroring CHANGELOG.md.
// A user reading "closed the three module-14 isolation findings" learns
// nothing; a developer reading "revisión de mantenimiento" loses the trail.
// New entries carry both; About falls back to `summary` if `resumen` is
// missing, so forgetting one degrades instead of rendering blank.
export const CHANGELOG = [
  { version: '2.0.23', date: '2026-10-05', resumen: 'Revisión de mantenimiento: el manual de usuario seguía describiendo el selector de negocio que se quitó hace casi un mes, y no mencionaba la verificación por correo ni la unión por código con aprobación de la versión anterior. Corregido. También se actualizaron tres dependencias por seguridad.', summary: 'Scheduled full audit. docs/USER_MANUAL.md and src/lib/manual.js still described the business switcher removed in module 18 (2026-09-10) and claimed a user could belong to multiple businesses — both contradict the current one-business-per-account model (409 on createBusiness/acceptInvitation). Fixed, and added the missing v2.0.22 coverage (email OTP verification, join-by-code-with-approval) to both. npm audit fix (non-breaking) patched brace-expansion/dompurify/moment; react-router stays deferred. Live schema verification: 19 entities, zero field-by-field drift from repo, and the long-pending Membership deploy:entities finally ran (no longer in the deployed schema). No isolation or RLS findings; validate:rls/permissions/functions, build, check:secrets and the one existing test file (joinRequestRules, 6/6) all pass.' },
  { version: '2.0.22', date: '2026-09-30', resumen: 'Ahora, al crear tu cuenta con correo y contraseña, te pedimos el código de 6 dígitos que te llega por correo. Y quien se une al equipo de un negocio con su código queda en espera hasta que el administrador lo apruebe y elija su rol.', summary: 'Email OTP verification step on Register/Login (register() now takes an object; auth.login did not exist and is replaced by loginViaEmailPassword). Join-by-code now creates a pending JoinRequest (new entity, service-role writes only) resolved by manageJoinRequest: the tenant admin approves choosing the role from a whitelist, or rejects; Team page lists pending requests.' },
  { version: '2.0.21', date: '2026-09-28', resumen: 'Revisión de mantenimiento: se verificó de nuevo, contra el sistema real, que las reglas de seguridad entre negocios siguen exactamente como deben. Sin cambios visibles en la app.', summary: 'Scheduled full audit, seven days after v2.0.20 with only a clean dependency bump in between. First field-by-field automated diff of every entity\'s RLS (create/read/update/delete plus per-field locks) against the live Base44 schema found zero drift across all 18 repo entities. CI and the production smoke test are green (one isolated smoke failure did not reproduce). No code defects, no isolation findings, no new gaps. Membership\'s pending removal and the module 9 (automated QA) gap are unchanged from v2.0.20.' },
  { version: '2.0.20', date: '2026-09-21', resumen: 'La app volvió a funcionar para quien no ha iniciado sesión: el arreglo de la versión anterior estaba listo desde hace diez días pero nunca se había publicado. También se confirmó, contra el sistema real, que los bloqueos de seguridad de roles y de licencia ya vigentes están funcionando en producción.', summary: 'Scheduled full audit. Found Production smoke test red on every run since v2.0.19 merged (10 days) — anonymous visitors were still bouncing to Base44\'s generic /login. The v2.0.19 fix was correct and already synced to the Base44 workspace, just never published; deployed it and confirmed via a fresh smoke-test run: green, all 7 checks, first time since 2026-09-10. Separately, live verification against the deployed Base44 schema (not just the repo .jsonc) confirmed the Module 1 (Business license fields) and Module 19 (User role/tenant fields) write locks are actually deployed and correct — previously only "not verified" from this environment. No code defects found. Two pre-existing gaps named for the first time: the retired Membership entity is still live in production (0 rows, awaiting a human-run destructive deploy:entities) and Module 9 (automated QA) was never actually built.' },
  { version: '2.0.19', date: '2026-09-10', resumen: 'Al entrar sin sesión, la app ya te lleva a su propia pantalla de inicio de sesión. Antes te sacaba a una página genérica de la plataforma, y por eso la app no llegaba a cargar para quien no había entrado todavía.', summary: 'Ten call sites still used base44.auth.redirectToLogin(), sending every anonymous visitor to Base44\'s platform-served /login so the Puntos+ SPA never mounted. This — not a deploy gap — is what kept the production smoke test red for nine days. New src/lib/goToLogin.js is the single owner of that navigation.' },
  { version: '2.0.18', date: '2026-09-09', resumen: 'Nueva pantalla "Acerca de": manual de usuario buscable, novedades de cada versión y a quién escribir. La sesión ahora avisa antes de cerrarse por inactividad, y en tu perfil puedes ver y cerrar las sesiones abiertas en otros dispositivos.', summary: 'Modules 19-23 of the ACACIA portfolio standard: lock rationale in every field description, session control (idle warning + device list + 48h stale-session reap), the About screen, no write decision taken from auth.me()\'s cached view (13 backend functions), and nav chrome surviving a reload.' },
  { version: '2.0.16', date: '2026-09-07', resumen: 'Revisión de mantenimiento: actualizaciones de seguridad de dependencias y correcciones internas. Sin cambios visibles en la app.', summary: 'Scheduled audit found production has not been serving the deployed code for at least 7 days (module 12\'s theme switcher is missing live — needs npm run deploy:site, not done here). Patched 4 dependency advisories (fflate, postcss-selector-parser, @humanfs/node, browserslist); react-router\'s advisory stays deferred pending a manual v7 migration. Documented the theme switcher in the user manual.' },
  { version: '2.0.15', date: '2026-08-24', resumen: 'Refuerzos de aislamiento entre negocios en el movimiento de puntos y en el código QR del monedero. Tu QR ahora sólo lo puede regenerar la app, no el navegador.', summary: 'Closed the three module-14 isolation findings: earnPoints/burnPoints now require the account\'s own tenant to match the store\'s, qr_token is locked from client writes (with a new refreshQrToken function backing Wallet.jsx\'s refresh), and LoyaltyAccount.business_id/store_id can no longer be written to a foreign tenant.' },
  { version: '2.0.14', date: '2026-08-18', resumen: 'La app muestra su versión y sus novedades desde dentro.', summary: 'Added an in-app version/changelog display and a real health-check endpoint audit (acaciaControl\'s ping action already existed and works — no code change needed there).' },
  { version: '2.0.13', date: '2026-08-17', resumen: 'Correcciones de permisos dentro de un mismo negocio, avisos que no se guardaban y errores al generar pases de monedero.', summary: 'Same-tenant RLS over-permission, notification-preference gap, wallet/email crash guards.' },
  { version: '2.0.12', date: '2026-08-10', resumen: 'Se corrigió que una misma venta pudiera acumular puntos dos veces.', summary: 'Points-dedup gap on earnPoints, dependency patches.' },
  { version: '2.0.11', date: '2026-07-28', resumen: 'Correcciones de seguridad en invitaciones y en el manejo de puntos.', summary: 'Cross-tenant invitation leak, scheduled-function auth, points dedup hardening.' },
  { version: '2.0.10', date: '2026-07-27', resumen: 'Refuerzos de aislamiento entre negocios e integridad de los saldos de puntos.', summary: 'Tenant-isolation and points-integrity hardening.' },
  { version: '2.0.9', date: '2026-07-20', resumen: 'Revisión de mantenimiento y verificación de correcciones anteriores.', summary: 'Release-hygiene audit: sync release metadata, verify prior fix is live.' },
];
